# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

os:
  editPreset: "nvim"
gui:
  border: rounded
  showFileTree: false # Just the list the files changed
  showCommandLog: false
  commitHashLength: 0 # Hide SHAs in commit log
  expandFocusedSidePanel: true
  shrinkSidePanelsToContent: true
  expandedSidePanelWeight: 3
  enlargedSideViewLocation: top
  sidePanels:
    - [files, worktrees, stash, submodules]
    - [branches, remotes, tags]
    - [commits, reflog]
    - [status]
git:
  diffRenderers:
    - command: hunk pager --transparent-bg
  overrideGpg: true
