schema_version = 7

[app_settings]
launch_at_login = false
check_for_updates = true
auto_install_updates = false
update_prompt_seen = true
show_in_menu_bar = true
capture_mouse_events = true
auto_download_assets = true
asset_source = "automatic"
thumbwheel_sensitivity = 14
appearance = "system"
smooth_scroll = false
vertical_scroll_sensitivity = 14
app_icon = "openlogi"
ui_scale = "normal"
device_view_mode = "grid"

[devices]

[devices."unit:f6545a54".identity]
display_name = "MX Ergo"
codename = "MX Ergo Multi-Device Trackball "
kind = "trackball"

[devices."unit:f6545a54".identity.model_info]
entity_count = 3
unit_id = [
    0,
    0,
    0,
    0,
]
model_ids = [
    45085,
    16495,
    0,
]
extended_model_id = 0

[devices."unit:f6545a54".identity.model_info.transports]
usb = false
equad = true
btle = true
bluetooth = false

[devices."unit:f6545a54".identity.capabilities]
buttons = true
pointer = false
lighting = false
scroll_inversion = false
hires_wheel = false
thumbwheel = false
haptic_feedback = false
haptic_panel = false

[keyboard]

[devices."unit:f6545a54".links."direct:046d:b01d"]

[devices."unit:f6545a54".bindings]
Forward = "PreviousDesktop"
WheelTiltLeft = "MouseBack"
WheelTiltRight = "MouseForward"
Back = "NextDesktop"

[devices."unit:f6545a54".disabled_gestures.Forward]
Up = "MissionControl"
Down = "ShowDesktop"
Left = "PrevTab"
Right = "NextTab"
Click = "BrowserForward"
